services:
  strapi:
    build: .
    image: strapi-blog
    ports:
      - "3000:3000"
    
    env_file:
      - .env
    
    volumes:
      - ./database:/opt/app/database
      - ./uploads:/opt/app/public/uploads

    
    restart: unless-stopped